# Generated by Django 4.2.3 on 2024-03-14 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GerenteGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='Cadastro de Pessoa Física')),
                ('telefone', models.CharField(max_length=11, unique=True, verbose_name='Telefone')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=50, verbose_name='Senha')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gerente Geral',
                'verbose_name_plural': 'Gerentes Gerais',
            },
        ),
        migrations.CreateModel(
            name='GerenteLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='Cadastro de Pessoa Física')),
                ('telefone', models.CharField(max_length=11, unique=True, verbose_name='Telefone')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=50, verbose_name='Senha')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gerente Local',
                'verbose_name_plural': 'Gerentes Locais',
            },
        ),
        migrations.DeleteModel(
            name='UserProfileExample',
        ),
    ]
