# Generated by Django 4.2.3 on 2024-02-16 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_gerente_funcionario_empresa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileExample',
        ),
    ]
