# Generated by Django 4.2.3 on 2024-02-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_userprofileexample'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nome',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
