# Generated by Django 4.2.3 on 2024-02-16 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_empresa_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='phone_number',
            new_name='telefone',
        ),
    ]
