# Generated by Django 4.2.3 on 2024-02-16 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_address_empresa_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='birth_date',
        ),
    ]
