# Generated by Django 4.2.3 on 2024-02-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_empresa_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='test',
            field=models.CharField(default='', max_length=14),
        ),
    ]
