# Generated by Django 4.2.3 on 2024-02-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_test_empresa_cnpj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='birth_date',
            new_name='aniversario',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='phone_number',
            new_name='telefone',
        ),
        migrations.RenameField(
            model_name='gerente',
            old_name='birth_date',
            new_name='aniversario',
        ),
        migrations.RenameField(
            model_name='gerente',
            old_name='address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='gerente',
            old_name='phone_number',
            new_name='telefone',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='gerente',
            name='cpf',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AddField(
            model_name='gerente',
            name='nome',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
