# Generated by Django 4.2.3 on 2024-02-16 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_birth_date_funcionario_aniversario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='aniversario',
        ),
        migrations.RemoveField(
            model_name='gerente',
            name='aniversario',
        ),
    ]
