# Generated by Django 4.2.3 on 2024-02-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_funcionario_aniversario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='plano',
            field=models.CharField(default='', max_length=20),
        ),
    ]
