# Generated by Django 4.2.3 on 2024-03-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da empresa')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ da empresa')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Email da empresa')),
            ],
        ),
    ]
