# Generated by Django 4.2.3 on 2024-03-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamentos', '0002_estacionamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='plano',
            field=models.IntegerField(default=0, verbose_name='Plano de assinatura'),
        ),
        migrations.DeleteModel(
            name='Estacionamento',
        ),
    ]
