# Generated by Django 4.2.3 on 2024-03-16 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamentos', '0003_empresa_plano_delete_estacionamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100, verbose_name='Nome da rua do estacionamento')),
                ('numero', models.CharField(max_length=10, verbose_name='Número do estacionamento')),
                ('bairro', models.CharField(max_length=50, verbose_name='Nome do bairro')),
                ('cidade', models.CharField(max_length=50, verbose_name='Nome da cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='UF do estado')),
                ('capacidade', models.IntegerField(verbose_name='Capacidade de veiculos do estacionamento')),
                ('lotacao', models.IntegerField(default=0, verbose_name='Número veiculos no estacionamento')),
                ('idEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamentos.empresa', verbose_name='Id da empresa proprietária do estacionamento')),
            ],
        ),
    ]
