# Generated by Django 4.2.3 on 2024-03-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamentos', '0004_estacionamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Email da empresa'),
        ),
    ]
