# Generated by Django 4.2.3 on 2024-03-20 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamentos', '0005_alter_empresa_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeiculoEstacionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEntrada', models.DateTimeField(auto_now_add=True, verbose_name='Data de entrada')),
                ('placaCarro', models.CharField(max_length=7, unique=True, verbose_name='Placa do carro')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('idEstacionamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamentos.estacionamento', verbose_name='Id do estacionamento')),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('placaCarro', models.CharField(max_length=7, verbose_name='Placa do carro')),
                ('dataEntrada', models.DateTimeField(verbose_name='Data de entrada')),
                ('dataSaida', models.DateTimeField(auto_now_add=True, verbose_name='Data de saída')),
                ('idEstaionamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamentos.estacionamento', verbose_name='Id do estacionamento')),
            ],
        ),
    ]
