# Generated by Django 4.2.3 on 2024-03-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamentos', '0006_veiculoestacionado_historico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historico',
            old_name='idEstaionamento',
            new_name='idEstacionamento',
        ),
    ]
