# Generated by Django 4.2.3 on 2024-03-25 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamentos', '0008_locacao_remove_veiculoestacionado_idestacionamento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='estacionamento',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='locacao',
            options={'ordering': ['id']},
        ),
    ]
