# Generated by Django 4.2.3 on 2024-02-16 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamentos', '0002_enderreco'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enderreco',
            new_name='Endereco',
        ),
    ]
