# Generated by Django 4.2.3 on 2024-02-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamentos', '0003_rename_enderreco_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacionamento',
            name='idEmpresa',
        ),
        migrations.RemoveField(
            model_name='estacionamento',
            name='idEndereco',
        ),
        migrations.RemoveField(
            model_name='estacionamento',
            name='idGerente',
        ),
        migrations.RemoveField(
            model_name='estacionamento',
            name='idfuncionario',
        ),
        migrations.RemoveField(
            model_name='estacionamento',
            name='nome',
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(max_length=50),
        ),
    ]
