# Generated by Django 4.2.3 on 2024-02-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamentos', '0004_remove_estacionamento_idempresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamento',
            name='test',
            field=models.CharField(default='', max_length=100),
        ),
    ]
