# Generated by Django 4.2.3 on 2024-02-16 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_userprofileexample'),
        ('estacionamentos', '0005_estacionamento_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamento',
            name='idEmpresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.empresa'),
        ),
        migrations.AddField(
            model_name='estacionamento',
            name='idEndereco',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='estacionamentos.endereco'),
        ),
        migrations.AddField(
            model_name='estacionamento',
            name='idGerente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.gerente'),
        ),
        migrations.AddField(
            model_name='estacionamento',
            name='idfuncionario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.funcionario'),
        ),
    ]
