# Generated by Django 4.2.3 on 2024-02-16 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamentos', '0006_estacionamento_idempresa_estacionamento_idendereco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacionamento',
            name='test',
        ),
    ]
