# Generated by Django 4.2.3 on 2024-02-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamentos', '0008_alter_estacionamento_idempresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='rua',
            field=models.CharField(default='', max_length=100),
        ),
    ]
